### PR TITLE
WIP: Return to form

### PR DESCRIPTION
**Pull request by msmith-techempower**

### CODE REVIEW

**Comment by NateBrady23** [comment]
Now that we've removed `state` from the action call, we should be consistent with our examples:

```
      <button className="inc" onClick={() => actions.increment()} />
      <button className="dec" onClick={() => actions.decrement()} />
```

Or:

```
      <button className="inc" onClick={actions.increment} />
      <button className="dec" onClick={actions.decrement} />
```

**Comment by msmith-techempower** [comment]
I don't think it's an issue with consistency; it just happens that because there are no arguments, you can have the `onClick` handler pass directly to the function.

If I HAD to pick one, it would be the former for clear illustrative purposes.

**Comment by NateBrady23** [comment]
Ok, we have a few examples where we do the former and the latter; I don't care either way.

**Review by NateBrady23 — APPROVED** [review]

**Comment by msmith-techempower** [comment]
Closed in favor of #28

**Pull request closed without merging**
